/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.degoo.libjingle4j.proxy;

public class DataTransferAppProxy {
  private long swigCPtr;
  private boolean swigCMemOwn;

  private DataTransferAppProxy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DataTransferAppProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibjingleDataTransferJNI.delete_DataTransferAppProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataTransferAppProxy() {
    this(LibjingleDataTransferJNI.new_DataTransferAppProxy(), true);
  }

  public void login(String nodeID, String password, String xmppServer, int port, int time_out) {
    LibjingleDataTransferJNI.DataTransferAppProxy_login(swigCPtr, this, nodeID, password, xmppServer, port, time_out);
  }

  public void logout() {
    LibjingleDataTransferJNI.DataTransferAppProxy_logout(swigCPtr, this);
  }

  public void send(byte[] BYTE, long len, String remoteNodeID) {
    LibjingleDataTransferJNI.DataTransferAppProxy_send(swigCPtr, this, BYTE, len, remoteNodeID);
  }

  public void setDebug(boolean isDebug) {
    LibjingleDataTransferJNI.DataTransferAppProxy_setDebug(swigCPtr, this, isDebug);
  }

  public void setStunAndRelayInfo(String stunAddr, int stunPort, String relayAddr, int relayPort) {
    LibjingleDataTransferJNI.DataTransferAppProxy_setStunAndRelayInfo(swigCPtr, this, stunAddr, stunPort, relayAddr, relayPort);
  }

  public void setReceiver(ReceiverCallback cb) {
    LibjingleDataTransferJNI.DataTransferAppProxy_setReceiver(swigCPtr, this, ReceiverCallback.getCPtr(cb), cb);
  }

  public void deleteReceiver() {
    LibjingleDataTransferJNI.DataTransferAppProxy_deleteReceiver(swigCPtr, this);
  }

  public boolean isReceiverInitialized() {
    return LibjingleDataTransferJNI.DataTransferAppProxy_isReceiverInitialized(swigCPtr, this);
  }

}
