/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.degoo.libjingle4j.proxy;

public enum ErrorCode {
  SessionTimeOut,
  SessionErrors,
  StreamReadError,
  StreamWriteError,
  InvalidReceiver,
  MalformedID,
  ReceiverUnavailable,
  NotifiedTunnelErrors,
  LoginTimeout;

  public final int swigValue() {
    return swigValue;
  }

  public static ErrorCode swigToEnum(int swigValue) {
    ErrorCode[] swigValues = ErrorCode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ErrorCode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ErrorCode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ErrorCode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ErrorCode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ErrorCode(ErrorCode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

